#new comment

version: '3.9'

services:
  #nginx
  nginx-service:
    image: nginx:stable-alpine
    container_name: nginx-container
    ports:
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT}:443
    volumes:
      - ./app:${PROJECT_DIR}
      - ./docker/certbot/www:/var/www/certbot/
      - ./docker/certbot/conf/:/etc/letsencrypt/
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - mysql8-service
      - php8-service

  #certbot
  certbot:
    image: certbot/certbot
    volumes:
      - ./docker/certbot/conf/:/etc/letsencrypt/
      - ./docker/certbot/www:/var/www/certbot/

  # mysql
  mysql8-service:
    image: mysql:8
    container_name: mysql8-container
    ports:
      - '4306:3306'
    volumes:
      - ./docker/mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always # always restart unless stopped manually
    environment:
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'

  # php
  php8-service:
    build:
      context: ./docker/php
    container_name: php8-container
    ports:
      - '9000:9000'
    volumes:
      - ./app:${PROJECT_DIR}

  # node
  node-service:
    image: node:latest
    container_name: node-container
    volumes:
      - ./app:${PROJECT_DIR}
    working_dir: ${PROJECT_DIR}
